# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.5-node-browsers
        environment:
          MIX_ENV: test
      - image: circleci/postgres:9.4-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: paironauts_test
          POSTGRES_PASSWORD:

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - run: mix do deps.get, compile
      - run: mix ecto.create

      - run: cd assets && npm install
      - run: cd ..

      - run: |
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb
          export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
          curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin
          google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

      - run:
          name: Start chromedriver
          command: |
            chromedriver --verbose background: true

      - run: mix test
